output_path: dummy-tracking-env/single-fleeing-agent-fixed-location
mode: param_study
wait_time_between_jobs_sec: 0.1
number_of_jobs:  # indicates number of seeds per parameter value
  - 3
base_config_files:
  - src/scripts/config/dummy_fleeing_ppo.yml
job_configs:
  - command: python3.8 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase-dummy-tracking-env
    cpus: 2
    gpus: 0
    cpu_mem_gb: 3
    disk_mem_gb: 52
    wall_time_s: 10 * 3600
    nice: true
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: true
