output_path: encoder_decoder/discriminator
mode: lr_discirminator_line_world
wait_time_between_jobs_sec: 0.1
job_configs:
  - command: python3.8 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 2
    gpus: 1
    gpu_mem_mb: 2900
    cpu_mem_gb: 19
    disk_mem_gb: 52
    wall_time_s: 6 * 60 * 60
    nice: true
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: true
    save_before_wall_time: true
    extra_requirements: ( Has_ssse3 == True )
number_of_jobs:
  - 1
base_config_files:
    - src/scripts/config/il_train_line_world_discriminator.yml
