world_name: cube_world
max_duration: 300
starting_height: 0
delay_evaluation: 0.1
goal:
  x:
    min: 1.7
    max: 2.2
  y:
    min: -1
    max: 1
  z:
    min: -1
    max: 1
waypoints:
  - [0, 4]
  - [4, 4]
  - [4, 0]
  - [0, 0]
waypoint_reached_distance: 0.25
background_file: src/sim/ros/gazebo/background_images/cube_world_2_2_10.jpg