world_name: straight_corridor
max_duration: 300
starting_height: 0
delay_evaluation: 0.1
goal:
  x:
    min: -0.5
    max: 0.5
  y:
    min: 8
    max: 9
  z:
    min: -1
    max: 1
waypoint_reached_distance: 0.25
waypoints:
  - [0, 2]
  - [0, 4]
  - [0, 6]
  - [0, 8]
  - [0, 9]
background_file: src/sim/ros/gazebo/background_images/straight_corridor_0_4_20.jpg
reward:
  add_distance_from_start: True
  duration: -1
  collision: -1