world_name: debug
max_duration: 60
delay_evaluation: 3.0
flying_height: 1
goal:
  x:
    min: 1.7
    max: 2.2
  y:
    min: 1.7
    max: 2.2
  z:
    min: 0.2
    max: 5.
waypoints:
  - [0, 2]
  - [2, 2]
waypoint_reached_distance: 0.2
reward:
  on_collision:
    termination: 'Failure'
    weights:
      constant: -100
  goal_reached:
    termination: 'Success'
    weights:
      constant: 100
  step:
    termination: 'NotDone'
    weights:
      constant: 10
