world_name: test_world
max_duration: -1
starting_height: 0
delay_evaluation: 0.1
goal:
  x:
    min: 0.7
    max: 1.2
  y:
    min: 0.7
    max: 1.2
  z:
    min: -1
    max: 1
waypoints:
  - [0, 1]
  - [1, 1]
waypoint_reached_distance: 0.1