supervision_topic: '/control_mapper/supervision'
rate_fps: 60
mapping:
  Unknown:
    command: '/actor/keyboard/cmd_vel'
  Terminated:
    command: '/actor/keyboard/cmd_vel'
  Running:
    command: '/actor/ros_expert/cmd_vel'
    supervision: '/actor/keyboard/cmd_vel'
  TakeOff: {}
  TakenOver:
    command: '/actor/keyboard/cmd_vel'
  DriveBack: {}


#max_time
#current_time
#control_time
#aggressiveness