supervision_topic: '/control_mapper/supervision'
rate_fps: 60
mapping:
  Unknown: {}
  Terminated: {}
  Running:
    command: '/ros_python_interface/cmd_vel'
    supervision: '/actor/ros_expert/cmd_vel'
  TakeOff: {}
  TakenOver: {}
  DriveBack: {}
