
rate_fps: 60
noise:
  name: OUNoise
  args:
    dimension:
      - 6
      - 1
    seed: 1234
    mean: 0
    std: 0.25
    pullback: 0.2
mapping:
  Unknown:
    command: '/actor/keyboard/cmd_vel'
  Terminated:
    command: '/actor/keyboard/cmd_vel'
  Running:
    command: '/actor/ros_expert/cmd_vel'
  TakenOver:
    command: '/actor/keyboard/cmd_vel'
  DriveBack: {}


#max_time
#current_time
#control_time
#aggressiveness