supervision_topic: '/control_mapper/supervision'
rate_fps: 60
noise:
  name: OUNoise
  args:
    dimension:
      - 6
      - 1
    seed: 1234
    mean: 0
    std: 0.2
    pullback: 0.3
mapping:
  Unknown: {}
  Terminated: {}
  Running:
    command: '/actor/ros_expert'
    supervision: '/actor/neural_network'
  TakeOff:
    command: '/actor/ros_expert'
    supervision: '/actor/ros_expert'
  TakenOver:
    command: '/actor/keyboard'
    supervision: '/actor/drive_back'
  DriveBack:
    command: '/actor/drive_back'
    supervision: '/actor/drive_back'