architecture_config:
  architecture: cart_pole_4_2d_stochastic
  device: cpu
data_saver_config:
  clear_buffer_before_episode: false
  store_on_ram_only: false
environment_config:
  factory_key: GYM
  gym_config:
    random_seed: 123
    render: true
    world_name: CartPole-v0
  max_number_of_steps: -1
number_of_episodes: 10
number_of_epochs: 1
output_path: cart_pole_vpg
tensorboard: true
load_checkpoint_dir: cart_pole_vpg