output_path: adversarial_agents_stacked_ros
number_of_epochs: 100
episode_runner_config:
  number_of_episodes: 5
  train_every_n_steps: -1
architecture_config:
  architecture: adversarial_actor_critic_stacked_ros
  device: cpu
  initialisation_type: orthogonal
  random_seed: 123
environment_config:
  factory_key: ROS
  max_number_of_steps: 200
  ros_config:
    info:
      - frame
    observation: modified_state
    action_topic: python
    num_action_publishers: 2
    visible_xterm: true
    step_rate_fps: 100
    ros_launch_config:
      random_seed: 123
      robot_name: stacked_drone_sim
      fsm_mode: TakeOverRun
      fsm: true
      control_mapping: true
      distance_tracking_fleeing_m: 0.5
      modified_state_publisher: true
      modified_state_publisher_mode: CombinedGlobalPoses
      modified_state_frame_visualizer: true
      waypoint_indicator: false
      control_mapping_config: python_adversarial
      world_name: tracking_stacked
      gazebo: True
      x_pos: 0.0
      y_pos: 0.0
      z_pos: 0.0
      yaw_or: 0
      starting_height_tracking: 4.0
      starting_height_fleeing: 1.0
    actor_configs:
      - name: altitude_control
data_saver_config:
  clear_buffer_before_episode: true
  store_on_ram_only: true
tensorboard: true
tb_render_every_n_epochs: 1
save_checkpoint_every_n: 5
trainer_config:
  criterion: MSELoss
  actor_learning_rate: 0.001
  critic_learning_rate: 0.0001
  scheduler_config:
    number_of_epochs: 100
  gradient_clip_norm: -1
  optimizer: Adam
  data_loader_config:
    batch_size: 32
    random_seed: 123
  device: cpu
  discount: 0.99
  factory_key: APPO
  gae_lambda: 0.95
  phi_key: gae
  entropy_coefficient: 0.01
  max_actor_training_iterations: 50
  max_critic_training_iterations: 10
  epsilon: 0.1
  use_kl_stop: true
  kl_target: 0.01
