teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 3  # Right thumb stick (up/down)
        target: linear.x
        scale: 0.3
        offset: 0.0
      -
        axis: 2  # Right thumb stick (left/right)
        target: linear.y
        scale: 0.1

        offset: 0.0
      -
        axis: 1  # Left thumb stick (up/down)
        target: linear.z
        scale: 0.2
        offset: 0.0
      -
        axis: 0  # Left thumb stick (left/right)
        target: angular.z
        scale: 0.5
        offset: 0.0
#  camera:
#    type: topic
#    message_type: "geometry_msgs/Twist"
#    topic_name: /bebop/camera_control
#    axis_mappings:
#      -
#        axis: 5  # Left D-Pad (up/down)
#        target: angular.y
#        scale: 90.0
#        offset: 0.0
#      -
#        axis: 4  # Left D-Pad (left/right)
#        target: angular.z
#        scale: -90.0
#        offset: 0.0
  takeoff:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: /bebop/takeoff
    deadman_buttons: [9]  #  start button
    axis_mappings: []
  land:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: /bebop/land
    deadman_buttons: [1]  # X-button
    axis_mappings: []
  emergency:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: /bebop/emergency
    deadman_buttons: [4] # L1
    axis_mappings: []
  flattrim:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: /bebop/flattrim
    deadman_buttons: [0] # Square
    axis_mappings: []
  go:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: /fsm/go
    deadman_buttons: [3] #traingle
    axis_mappings: []
  overtake:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: /fsm/overtake
    deadman_buttons: [2] # o
    axis_mappings: []
  toggle_camera_forward_down:
    type: method
    buttons: [7]  # R2
