specs:
  command_topic: '/actor/keyboard/cmd_vel'
  message: "
             Reading from the keyboard  and Publishing to Twist!
             ---------------------------
             Moving around:
               u    i    o
               j    k    l
               m    ,    .
             CTRL-C to quit
         "
  speed: 0.2
  turn: 0.8
  rate_fps: 10
  moveBindings:
    i:
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    o:
    - 1
    - 0
    - 0
    - 0
    - 0
    - -1
    j:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    l:
    - 0
    - 0
    - 0
    - 0
    - 0
    - -1
    u:
    - 1
    - 0
    - 0
    - 0
    - 0
    - 1
    ',':
    - -1
    - 0
    - 0
    - 0
    - 0
    - 0
    .:
    - -1
    - 0
    - 0
    - 0
    - 0
    - 1
    ':':
    - -1
    - 0
    - 0
    - 0
    - 0
    - -1
  topicBindings:
    g: '/fsm/go'
    f: '/fsm/overtake'
