robot_type: 'quadrotor_real'
command_topic: '/bebop/cmd_vel'
camera_sensor:
  topic: '/bebop/image_raw'
  type: 'Image'
  stats:
    height: 200
    width: 200
    depth: 1
position_sensor:
  topic: '/bebop/odom'
  type: 'Odometry'
gps_position_sensor:
  topic: '/bebop/fix'
  type: 'NavSatFix'
takeoff: '/bebop/takeoff'
land: '/bebop/land'
emergency: '/bebop/emergency'
flattrim: '/bebop/flattrim'