robot_type: quadrotor_sim
takeoff_action: /action/takeoff
command_topic: /cmd_vel
camera_sensor:
  topic: /forward/camera/image
  type: Image
  stats:
    height: 200
    width: 200
    depth: 3
position_sensor:
  topic: /ground_truth/state
  type: Odometry
depth_sensor:
  topic: /scan
  type: LaserScan
collision_sensor:
  topic: /command/wrench
  type: WrenchStamped