robot_type: quadrotor_sim
takeoff_action: /action/takeoff
command_topic: /cmd_vel
camera_sensor:
  topic: /down/camera/image
  type: Image
  stats:
    height: 200
    width: 200
    depth: 1
position_sensor:
  topic: /ground_truth/state
  type: Odometry
collision_sensor:
  topic: /command/wrench
  type: WrenchStamped