model_name: quadrotor
takeoff_action: /action/takeoff
command_topic: /cmd_vel
camera_sensor:
  topic: /down/image_raw
  type: Image
  stats:
    height: 200
    width: 200
    depth: 3
position_sensor:
  topic: /ground_truth/state
  type: Odometry
collision_sensor:
  topic: /command/wrench
  type: WrenchStamped