robot_type: 'quadrotor'
command_topic: '/cmd_vel'
sensors:
  - 'forward_camera'
  - 'depth_scan'
  - 'odometry'
forward_camera_topic: '/wa/camera/image_raw'
forward_camera_type: 'Image'
forward_camera_stats:
  height: 128
  width: 128
  depth: 3
depth_scan_topic: '/scan'
depth_scan_type: 'LaserScan'
depth_scan_stats:
  field_of_view: 120
  num_smooth_bins: 4
  max_depth: 1
  min_depth: 0.1
collision_depth: 0.5
odometry_topic: '/odom'
odometry_type: 'Odometry'
wrench_topic: /command/wrench