robot_type: 'turtlebot'
command_topic: '/cmd_vel'
depth_sensor:
  topic: '/scan'
  type: 'LaserScan'
  stats:
    field_of_view: 120
    num_smooth_bins: 4
    max_depth: 4
    min_depth: 0.1
position_sensor:
  topic: '/odom'
  type: 'Odometry'
camera_sensor:
  topic: '/raspicam_node/image/compressed'
  type: 'CompressedImage'
  stats:
    height: 200
    width: 200
    depth: 1
