robot_type: 'turtlebot'
command_topic: '/cmd_vel'
sensors:
#  - 'forward_camera'
#forward_camera_topic: '/wa/camera/image_raw'
#forward_camera_type: 'Image'
#forward_camera_stats:
#  height: 128
#  width: 128
#  depth: 3
  - 'odometry'
#  - 'depth_scan'
#depth_scan_topic: '/scan'
#depth_scan_type: 'LaserScan'
#depth_scan_stats:
#  field_of_view: 120
#  num_smooth_bins: 4
#  max_depth: 4
#  min_depth: 0.1
odometry_topic: '/odom'
odometry_type: 'Odometry'